// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var canvas, lat, long;

  lat = document.getElementById("lat");

  long = document.getElementById("long");

  canvas = document.getElementById("display");

  window.addEventListener('load', this.canvasApp, false);

  lat.addEventListener('change', this.updateLabels, false);

  long.addEventListener('change', this.updateLabels, false);

  canvas.addEventListener('mousemove', this.mousehandler, false);

}).call(this);
